const router = require('express').Router();
const { body, param } = require('express-validator');
const auth = require('../middleware/auth');
const validate = require('../middleware/validate');
const controller = require('../controllers/favouriteController');
router.use(auth);
router.post('/', [body('userId').isMongoId(), body('siteId').isString().notEmpty()], validate, controller.add);
router.get('/:userId', [param('userId').isMongoId()], validate, controller.list);
router.delete('/:userId/:siteId', [param('userId').isMongoId(), param('siteId').notEmpty()], validate, controller.remove);
module.exports = router;
