import React, { useMemo } from 'react';
import { Alert, FlatList, Linking, Pressable, StyleSheet, Text, View } from 'react-native';
import HeritageImage from '../components/HeritageImage';
import PrimaryButton from '../components/PrimaryButton';
import { useHeritage } from '../context/HeritageContext';

export default function DetailsScreen({ item, onBack, onOpenTrail }) {
  const { favorites, visited, trail, toggleFavorite, toggleTrail, markVisited } = useHeritage();
  const details = useMemo(() => item ? [{ label: 'Location', value: item.location, icon: '⌖' }, { label: 'Category', value: item.category, icon: '◇' }, { label: 'Visitor timings', value: item.timings, icon: '◷' }, { label: 'Estimated visit', value: item.duration, icon: '◌' }, { label: 'Historical significance', value: item.description, icon: '✦', long: true }] : [], [item]);
  if (!item) return <View style={styles.empty}><Text style={styles.emptyText}>Select a heritage site to view its details.</Text><PrimaryButton onPress={onBack}>Back to Explore</PrimaryButton></View>;
  const saved = favorites.includes(item.id);
  const inTrail = trail.includes(item.id);
  const visit = visited.find(entry => entry.id === item.id);
  const openMap = async () => {
    const url = `https://www.google.com/maps/search/?api=1&query=${item.latitude},${item.longitude}`;
    try {
      const supported = await Linking.canOpenURL(url);
      if (!supported) throw new Error('Unsupported URL');
      await Linking.openURL(url);
    } catch (error) { Alert.alert('Unable to open map', 'We could not open a map app for this location. Please try again later.'); }
  };
  return <View style={styles.screen}><FlatList data={details} keyExtractor={row => row.label} contentContainerStyle={styles.content} ListHeaderComponent={<><Pressable onPress={onBack}><Text style={styles.back}>← Back to explore</Text></Pressable><View style={styles.imageWrap}><HeritageImage uri={item.image} style={styles.image} accessibilityLabel={item.name} /></View><View style={styles.titleRow}><View style={styles.titleCopy}><Text style={styles.title}>{item.name}</Text><Text style={styles.type}>{item.type} · {item.state}</Text>{item.unesco ? <Text style={styles.unesco}>UNESCO World Heritage Site</Text> : null}</View><Pressable style={styles.heartButton} onPress={() => toggleFavorite(item.id)}><Text style={styles.heart}>{saved ? '♥' : '♡'}</Text></Pressable></View><Text style={styles.intro}>{item.description}</Text></>} renderItem={({ item: row }) => <View style={[styles.infoCard, row.long && styles.longCard]}><Text style={styles.infoIcon}>{row.icon}</Text><View style={styles.infoCopy}><Text style={styles.infoLabel}>{row.label}</Text><Text style={styles.infoValue}>{row.value}</Text></View></View>} ListFooterComponent={<View style={styles.actions}><PrimaryButton onPress={() => { if (!inTrail) toggleTrail(item.id); onOpenTrail(); }}>{inTrail ? 'View My Trail' : 'Add to My Trail'}</PrimaryButton><Pressable style={styles.secondary} onPress={openMap}><Text style={styles.secondaryText}>View on Map</Text></Pressable><Pressable style={styles.visited} onPress={() => markVisited(item)}><Text style={styles.visitedText}>{visit ? `✓ Visited ${new Date(visit.visitedAt).toLocaleDateString()}` : '✓ Mark as visited'}</Text></Pressable></View>} /></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#F7EFE6' }, content: { padding: 16, paddingBottom: 30 }, back: { color: '#4B2E23', fontWeight: '800', marginBottom: 14 }, imageWrap: { borderRadius: 20, overflow: 'hidden', elevation: 5 }, image: { width: '100%', height: 235 }, titleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginTop: 16 }, titleCopy: { flex: 1 }, title: { color: '#4B2E23', fontSize: 25, fontWeight: '900', lineHeight: 31 }, type: { color: '#8B4A24', fontWeight: '700', marginTop: 5 }, unesco: { color: '#23805D', fontWeight: '900', marginTop: 7 }, heartButton: { width: 46, height: 46, borderRadius: 23, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFF' }, heart: { color: '#B9572B', fontSize: 28 }, intro: { color: '#6F594A', lineHeight: 21, marginVertical: 15 }, infoCard: { flexDirection: 'row', backgroundColor: '#FFF', borderRadius: 15, padding: 14, marginTop: 9, borderWidth: 1, borderColor: '#F0E2D4' }, longCard: { alignItems: 'flex-start' }, infoIcon: { color: '#B9572B', fontSize: 19, width: 30, textAlign: 'center' }, infoCopy: { flex: 1 }, infoLabel: { color: '#8B4A24', fontSize: 11, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 0.6 }, infoValue: { color: '#4B2E23', marginTop: 5, lineHeight: 20 }, actions: { marginTop: 20 }, secondary: { backgroundColor: '#D9B44A', alignItems: 'center', padding: 14, borderRadius: 12, marginTop: 10 }, secondaryText: { color: '#4B2E23', fontWeight: '900' }, visited: { alignItems: 'center', padding: 14 }, visitedText: { color: '#8B4A24', fontWeight: '800' }, empty: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 25, backgroundColor: '#F7EFE6' }, emptyText: { color: '#6F594A', marginBottom: 15 } });
