import React, { useMemo, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from 'react-native';
import { CATEGORIES } from '../data/sampleData';
import { useHeritage } from '../context/HeritageContext';
import SiteCard from '../components/SiteCard';

export default function ExploreScreen({ onOpenDetails }) {
  const { sites, isLoadingSites, sitesError, refreshSites } = useHeritage();
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('All');
  const filtered = useMemo(() => sites.filter(site => `${site.name} ${site.city} ${site.district} ${site.state} ${site.category}`.toLowerCase().includes(query.toLowerCase()) && (category === 'All' || site.category === category)), [sites, query, category]);
  const header = <><View style={styles.top}><View><Text style={styles.title}>Explore</Text><Text style={styles.subtitle}>Live heritage information from Wikipedia</Text></View></View><View style={styles.search}><Text>⌕</Text><TextInput value={query} onChangeText={setQuery} placeholder="Search by name or city" style={styles.input} /></View><FlatList horizontal data={CATEGORIES} keyExtractor={item => item} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips} renderItem={({ item }) => <Pressable style={[styles.chip, item === category && styles.chipOn]} onPress={() => setCategory(item)}><Text style={[styles.chipText, item === category && styles.chipTextOn]}>{item}</Text></Pressable>} /><Text style={styles.count}>{filtered.length} historical sites</Text></>;
  if (isLoadingSites && !sites.length) return <View style={styles.center}><ActivityIndicator size="large" color="#B9572B" /><Text style={styles.status}>Loading heritage sites from Wikipedia…</Text></View>;
  if (sitesError && !sites.length) return <View style={styles.center}><Text style={styles.error}>{sitesError}</Text><Pressable style={styles.retry} onPress={refreshSites}><Text style={styles.retryText}>Retry</Text></Pressable></View>;
  return <FlatList style={styles.screen} data={filtered} keyExtractor={site => site.id} numColumns={2} columnWrapperStyle={filtered.length ? styles.grid : undefined} contentContainerStyle={styles.list} ListHeaderComponent={header} renderItem={({ item }) => <SiteCard site={item} onPress={onOpenDetails} />} ListEmptyComponent={<Text style={styles.empty}>No heritage sites match this search.</Text>} refreshControl={<RefreshControl refreshing={isLoadingSites} onRefresh={refreshSites} tintColor="#B9572B" />} ListFooterComponent={sitesError ? <View style={styles.inlineError}><Text style={styles.error}>{sitesError}</Text><Pressable onPress={refreshSites}><Text style={styles.inlineRetry}>Retry</Text></Pressable></View> : null} />;
}
const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F7EFE6' }, list: { padding: 16, paddingBottom: 28 }, top: { marginBottom: 16 }, title: { fontSize: 27, color: '#4B2E23', fontWeight: '900' }, subtitle: { color: '#6F594A', marginTop: 3 }, search: { backgroundColor: '#FFF', borderRadius: 14, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center' }, input: { flex: 1, paddingVertical: 12, marginLeft: 8 }, chips: { paddingVertical: 14 }, chip: { backgroundColor: '#FFF8F0', borderRadius: 16, paddingHorizontal: 13, paddingVertical: 8, marginRight: 8 }, chipOn: { backgroundColor: '#B9572B' }, chipText: { color: '#6F594A', fontWeight: '700', fontSize: 12 }, chipTextOn: { color: '#FFF' }, count: { color: '#8B4A24', fontWeight: '800', marginBottom: 10 }, grid: { justifyContent: 'space-between' }, center: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 28, backgroundColor: '#F7EFE6' }, status: { color: '#6F594A', marginTop: 12, textAlign: 'center' }, error: { color: '#B23B2B', textAlign: 'center', lineHeight: 20 }, retry: { backgroundColor: '#4B2E23', borderRadius: 12, paddingHorizontal: 24, paddingVertical: 12, marginTop: 16 }, retryText: { color: '#FFF', fontWeight: '900' }, empty: { color: '#6F594A', textAlign: 'center', marginTop: 22 }, inlineError: { alignItems: 'center', paddingVertical: 18 }, inlineRetry: { color: '#B9572B', fontWeight: '900', marginTop: 8 },
});
