import React, { useEffect, useMemo, useState } from 'react';
import { Alert, FlatList, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { CATEGORIES } from '../data/sampleData';
import { useHeritage } from '../context/HeritageContext';
import HeritageImage from '../components/HeritageImage';
import SiteCard from '../components/SiteCard';

const options = (label, values) => [label, ...new Set(values.filter(Boolean))];

export default function HomeScreen({ onOpenDetails, onOpenFavorites }) {
  const { sites, user, favorites, refreshSites, isLoadingSites } = useHeritage();
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState('All');
  const [state, setState] = useState('All States');
  const [district, setDistrict] = useState('All Districts');
  const [welcomed, setWelcomed] = useState(false);
  useEffect(() => { if (sites.length && !welcomed) { setWelcomed(true); Alert.alert('Welcome to Heritage Explorer', 'Search places by name, city, state or category.'); } }, [sites.length, welcomed]);
  const states = useMemo(() => options('All States', sites.map(site => site.state)), [sites]);
  const districts = useMemo(() => options('All Districts', sites.map(site => site.district)), [sites]);
  const results = useMemo(() => sites.filter(site => { const text = `${site.name} ${site.city} ${site.category} ${site.state} ${site.district}`.toLowerCase(); return text.includes(search.trim().toLowerCase()) && (category === 'All' || site.category === category) && (state === 'All States' || site.state === state) && (district === 'All Districts' || site.district === district); }), [sites, search, category, state, district]);
  const chips = (items, selected, update) => <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{items.map(item => <Pressable key={item} onPress={() => update(item)} style={[styles.chip, selected === item && styles.chipOn]}><Text style={[styles.chipText, selected === item && styles.chipTextOn]}>{item}</Text></Pressable>)}</ScrollView>;
  const day = sites[0];
  const header = <><View style={styles.header}><View><Text style={styles.kicker}>NAMASTE, {(user?.name || 'TRAVELLER').toUpperCase()}</Text><Text style={styles.title}>Explore heritage</Text></View></View><View style={styles.search}><Text style={styles.searchLabel}>Search</Text><TextInput value={search} onChangeText={setSearch} placeholder="Search name, city, state or category" style={styles.input} /></View>{day ? <View style={styles.day}><Text style={styles.dayKicker}>HERITAGE OF THE DAY</Text><HeritageImage uri={day.image} style={styles.dayImage} accessibilityLabel={day.name} /><Text style={styles.dayName}>{day.name}</Text><Text style={styles.dayMeta}>{day.city} · {day.category}</Text><Text style={styles.dayFact}>{day.description}</Text><Pressable onPress={() => onOpenDetails(day)}><Text style={styles.dayLink}>Explore site</Text></Pressable></View> : null}<View style={styles.row}><Text style={styles.section}>Heritage categories</Text><Text style={styles.count}>{results.length} places</Text></View>{chips(CATEGORIES, category, setCategory)}<Text style={styles.label}>STATE</Text>{chips(states, state, setState)}<Text style={styles.label}>DISTRICT</Text>{chips(districts, district, setDistrict)}<View style={styles.row}><Text style={styles.section}>Popular historical sites</Text><Pressable onPress={onOpenFavorites}><Text style={styles.saved}>Saved: {favorites.length}</Text></Pressable></View></>;
  return <View style={styles.screen}><FlatList data={results} keyExtractor={site => site.id} numColumns={2} renderItem={({ item: site }) => <SiteCard site={site} onPress={onOpenDetails} />} ListHeaderComponent={header} ListEmptyComponent={<View style={styles.empty}><Text style={styles.section}>No sites found</Text><Text>Try another search or filter.</Text></View>} columnWrapperStyle={styles.gridRow} contentContainerStyle={styles.content} nestedScrollEnabled keyboardDismissMode="on-drag" keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} refreshControl={<RefreshControl refreshing={isLoadingSites} onRefresh={refreshSites} />} /></View>;
}

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#F7EFE6' }, content: { padding: 16, paddingBottom: 28 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, kicker: { color: '#8B4A24', fontSize: 10, fontWeight: '900', letterSpacing: 1 }, title: { color: '#4B2E23', fontSize: 27, fontWeight: '900', marginTop: 4 }, menu: { backgroundColor: '#FFF', padding: 12, borderRadius: 20 }, search: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF', borderRadius: 15, paddingHorizontal: 14, marginTop: 16 }, searchLabel: { color: '#8B4A24', fontWeight: '800', marginRight: 8 }, input: { flex: 1, paddingVertical: 13, color: '#4B2E23' }, day: { backgroundColor: '#4B2E23', borderRadius: 18, padding: 14, marginTop: 16 }, dayKicker: { color: '#D9B44A', fontSize: 10, fontWeight: '900', letterSpacing: 1 }, dayImage: { width: '100%', height: 125, borderRadius: 12, marginTop: 10 }, dayName: { color: '#FFF', fontSize: 19, fontWeight: '900', marginTop: 10 }, dayMeta: { color: '#D9B44A', fontWeight: '800', marginTop: 4 }, dayFact: { color: '#EBDCD0', lineHeight: 19, marginTop: 7 }, dayLink: { color: '#FFF', fontWeight: '900', marginTop: 10 }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 20, marginBottom: 7 }, section: { color: '#4B2E23', fontSize: 17, fontWeight: '900' }, count: { color: '#8B4A24', fontWeight: '800' }, saved: { color: '#B9572B', fontWeight: '800' }, label: { color: '#8B4A24', fontSize: 10, fontWeight: '900', letterSpacing: 1, marginTop: 8 }, chips: { paddingBottom: 4 }, chip: { backgroundColor: '#FFF8F0', borderColor: '#E8D6C3', borderWidth: 1, borderRadius: 17, paddingHorizontal: 13, paddingVertical: 8, marginRight: 8 }, chipOn: { backgroundColor: '#B9572B', borderColor: '#B9572B' }, chipText: { color: '#6F594A', fontWeight: '700', fontSize: 12 }, chipTextOn: { color: '#FFF' }, grid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' }, empty: { backgroundColor: '#FFF', padding: 20, borderRadius: 15, marginTop: 10 } });
