import React from 'react';
import { Alert, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import PrimaryButton from '../components/PrimaryButton';
import { useHeritage } from '../context/HeritageContext';

export default function ProfileScreen({ onLogout }) {
  const { user, favorites, visited, sites, citiesExplored, categoriesExplored, updateProfile } = useHeritage();
  const [form, setForm] = React.useState({ name: user?.name || '', mobile: user?.mobile || '', category: user?.category || 'All' });
  const save = () => {
    if (!form.name.trim() || !/^\d{10}$/.test(form.mobile)) return Alert.alert('Check your details', 'Enter your name and a valid 10-digit mobile number.');
    updateProfile(form);
    Alert.alert('Profile updated', 'Profile updated successfully.');
  };
  const doLogout = () => Alert.alert('Logout and clear data', 'This clears your saved account, favourites, trail and visited sites from this device.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Clear all data', style: 'destructive', onPress: onLogout }]);
  const recentVisits = [...visited].reverse().slice(0, 3);
  return <ScrollView contentContainerStyle={styles.screen}><View style={styles.header}><Text style={styles.title}>My profile</Text></View><View style={styles.profileCard}><View style={styles.avatar}><Text style={styles.initial}>{(user?.name || 'H').charAt(0).toUpperCase()}</Text></View><Text style={styles.name}>{user?.name || 'Heritage Traveller'}</Text><Text style={styles.email}>{user?.email || ''}</Text></View><View style={styles.stats}><View style={styles.stat}><Text style={styles.value}>{visited.length}</Text><Text style={styles.label}>Total visited sites</Text></View><View style={styles.stat}><Text style={styles.value}>{citiesExplored}</Text><Text style={styles.label}>Cities explored</Text></View><View style={styles.stat}><Text style={styles.value}>{favorites.length}</Text><Text style={styles.label}>Favourites</Text></View></View><View style={styles.details}><Text style={styles.detailsTitle}>My Heritage Passport</Text><Text style={styles.detailsText}>Total Visited Sites: {visited.length} · Cities Explored: {citiesExplored} · Categories Explored: {categoriesExplored}</Text>{recentVisits.map(visit => <Text key={visit.id} style={styles.visit}>{sites.find(site => site.id === visit.id)?.name || visit.title} · {new Date(visit.visitedAt).toLocaleDateString()}</Text>)}</View><View style={styles.form}><Text style={styles.formTitle}>Edit profile</Text><TextInput style={styles.input} value={form.name} onChangeText={name => setForm({ ...form, name })} placeholder="Name" /><TextInput style={styles.input} value={form.mobile} onChangeText={mobile => setForm({ ...form, mobile })} placeholder="Mobile number" keyboardType="phone-pad" /><TextInput style={styles.input} value={form.category} onChangeText={category => setForm({ ...form, category })} placeholder="Preferred heritage category" /><PrimaryButton onPress={save}>Save profile</PrimaryButton></View><PrimaryButton onPress={doLogout} style={styles.logout}>Logout & Clear All Data</PrimaryButton></ScrollView>;
}
const styles = StyleSheet.create({ screen: { flexGrow: 1, padding: 16, backgroundColor: '#F7EFE6' }, header: { alignItems: 'flex-start' }, title: { color: '#4B2E23', fontSize: 26, fontWeight: '900' }, profileCard: { marginTop: 20, backgroundColor: '#4B2E23', borderRadius: 22, padding: 23, alignItems: 'center' }, avatar: { width: 78, height: 78, borderRadius: 39, backgroundColor: '#D9B44A', alignItems: 'center', justifyContent: 'center' }, initial: { fontSize: 34, color: '#4B2E23', fontWeight: '900' }, name: { color: '#FFF', fontSize: 21, fontWeight: '900', marginTop: 12, textTransform: 'capitalize' }, email: { color: '#EBDCD0', marginTop: 4 }, stats: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 15 }, stat: { width: '31%', backgroundColor: '#FFF', borderRadius: 16, paddingVertical: 15, alignItems: 'center', elevation: 2 }, value: { color: '#B9572B', fontSize: 22, fontWeight: '900' }, label: { color: '#6F594A', fontSize: 11, marginTop: 3, fontWeight: '700', textAlign: 'center' }, details: { backgroundColor: '#FFF', borderRadius: 18, padding: 18, marginTop: 17 }, detailsTitle: { color: '#4B2E23', fontWeight: '900', fontSize: 16 }, detailsText: { color: '#6F594A', lineHeight: 20, marginTop: 7 }, visit: { color: '#8B4A24', fontSize: 12, marginTop: 8, fontWeight: '700' }, form: { backgroundColor: '#FFF', borderRadius: 18, padding: 17, marginTop: 17 }, formTitle: { color: '#4B2E23', fontSize: 17, fontWeight: '900', marginBottom: 10 }, input: { borderWidth: 1, borderColor: '#E8D6C3', borderRadius: 11, padding: 12, marginBottom: 10, color: '#4B2E23' }, logout: { marginTop: 20 } });
