import React, { useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import PrimaryButton from '../components/PrimaryButton';
import { useHeritage } from '../context/HeritageContext';

export default function TrailScreen({ onOpenDetails }) {
  const { sites, trail, toggleTrail, saveTrail } = useHeritage(); const [time, setTime] = useState('Half day'); const [state, setState] = useState('All states'); const [city, setCity] = useState('All cities'); const [interest, setInterest] = useState('All');
  const choices = ['2 hours', 'Half day', 'Full day']; const states = useMemo(() => ['All states', ...new Set(sites.map(site => site.state))], [sites]); const cities = useMemo(() => ['All cities', ...new Set(sites.filter(site => state === 'All states' || site.state === state).map(site => site.city))], [sites, state]); const interests = ['All', 'Temples', 'Forts', 'Museums', 'Palaces', 'Monuments', 'UNESCO Sites']; const trailSites = sites.filter(site => trail.includes(site.id));
  const generate = () => { const matches = sites.filter(site => (state === 'All states' || site.state === state) && (city === 'All cities' || site.city === city) && (interest === 'All' || site.category === interest)).slice(0, time === '2 hours' ? 2 : time === 'Half day' ? 4 : 6); const nextTrail = [...new Set([...trail, ...matches.map(site => site.id)])]; matches.forEach(site => { if (!trail.includes(site.id)) toggleTrail(site.id); }); saveTrail(nextTrail); Alert.alert('Trail generated', `${matches.length} recommended site${matches.length === 1 ? '' : 's'} added to your plan.`); };
  const chooseState = value => { setState(value); setCity('All cities'); };
  const picker = (items, selected, update) => <ScrollView horizontal showsHorizontalScrollIndicator={false}>{items.map(item => <Pressable key={item} style={[styles.time, selected === item && styles.timeOn]} onPress={() => update(item)}><Text style={[styles.timeText, selected === item && styles.timeTextOn]}>{item}</Text></Pressable>)}</ScrollView>;
  return <View style={styles.screen}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} keyboardDismissMode="on-drag"><View style={styles.header}><View><Text style={styles.title}>My heritage trail</Text><Text style={styles.subtitle}>Build a journey that suits your time</Text></View></View><Text style={styles.label}>STATE</Text>{picker(states, state, chooseState)}<Text style={styles.label}>CITY</Text>{picker(cities, city, setCity)}<Text style={styles.label}>AVAILABLE VISIT TIME</Text>{picker(choices, time, setTime)}<Text style={styles.label}>HERITAGE INTEREST</Text>{picker(interests, interest, setInterest)}<PrimaryButton onPress={generate} style={styles.generate}>Generate Trail</PrimaryButton><View style={styles.summary}><Text style={styles.summaryTitle}>{trailSites.length ? `${trailSites.length} stops in your ${time.toLowerCase()} plan` : 'Your personalized trail'}</Text><Text style={styles.summaryText}>Choose a state for a multi-stop circuit or a city for nearby sites.</Text></View><Text style={styles.section}>Recommended sites</Text>{trailSites.length ? trailSites.map(site => <Pressable key={site.id} style={styles.site} onPress={() => onOpenDetails(site)}><View style={styles.siteMain}><Text style={styles.siteName}>{site.name}</Text><Text style={styles.siteInfo}>{site.location} · {site.duration}</Text></View><Text style={styles.addText}>View</Text></Pressable>) : <Text style={styles.none}>Generate a trail to see recommended sites.</Text>}</ScrollView></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#F7EFE6' }, content: { padding: 16, paddingBottom: 26 }, header: { flexDirection: 'row', justifyContent: 'space-between' }, title: { color: '#4B2E23', fontSize: 26, fontWeight: '900' }, subtitle: { color: '#6F594A', marginTop: 4 }, menu: { backgroundColor: '#FFF', padding: 12, borderRadius: 20 }, label: { color: '#8B4A24', fontSize: 11, fontWeight: '900', letterSpacing: 1, marginTop: 23 }, time: { backgroundColor: '#FFF8F0', borderRadius: 13, paddingVertical: 10, paddingHorizontal: 9, borderWidth: 1, borderColor: '#E8D6C3', marginRight: 8 }, timeOn: { backgroundColor: '#B9572B', borderColor: '#B9572B' }, timeText: { color: '#6F594A', fontWeight: '800', fontSize: 12 }, timeTextOn: { color: '#FFF' }, generate: { marginTop: 18 }, summary: { marginTop: 18, padding: 17, backgroundColor: '#4B2E23', borderRadius: 18 }, summaryTitle: { color: '#FFF', fontWeight: '900', fontSize: 17 }, summaryText: { color: '#EBDCD0', lineHeight: 19, marginTop: 7 }, section: { color: '#4B2E23', fontWeight: '900', fontSize: 17, marginTop: 22, marginBottom: 8 }, site: { flexDirection: 'row', alignItems: 'center', padding: 13, backgroundColor: '#FFF', borderRadius: 14, marginBottom: 9 }, siteMain: { flex: 1 }, siteName: { color: '#4B2E23', fontWeight: '900' }, siteInfo: { color: '#6F594A', fontSize: 12, marginTop: 5 }, addText: { color: '#8B4A24', fontWeight: '900' }, none: { color: '#6F594A', backgroundColor: '#FFF', padding: 16, borderRadius: 14, marginBottom: 12 } });
